18 gasometer
neonlabsorg/evm pull request #22
Opened 2021-06-17 15:48 UTC by vakond

Enabled gasometer. Note: no need for U256::from_big_endian for stack values in function dynamic_opcode_cost.

2021-06-18 09:52 UTC, anton-lisanin requested changes

2021-06-18 09:52 UTC, anton-lisanin commented on core/src/primitive_types.rs
> +        }
U256 internal representation is little endian. EVM uses big endian byte order.
When converting from U256 to byte array or to H256, you need to convert little to big endian.

2021-06-18 09:53 UTC, anton-lisanin commented on core/src/primitive_types.rs
> +        }
And implement `From` trait for conversion

2021-07-02 05:43 UTC, s-medvedev approved these changes

2021-07-02 10:33 UTC, anton-lisanin approved these changes

2021-07-02 10:34 UTC, merged